// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToPi(arg1) {
  return window['go']['main']['App']['ConnectToPi'](arg1);
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}
