// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToPi(arg1:string):Promise<string>;

export function SendCommand(arg1:string):Promise<string>;
