// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchCurrent() {
  return window['go']['main']['App']['FetchCurrent']();
}

export function FetchDeviceList(arg1) {
  return window['go']['main']['App']['FetchDeviceList'](arg1);
}

export function FetchMeterData(arg1, arg2) {
  return window['go']['main']['App']['FetchMeterData'](arg1, arg2);
}

export function SendCustomCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendCustomCommand'](arg1, arg2, arg3);
}
