// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchCurrent():Promise<number>;

export function FetchDeviceList(arg1:string):Promise<Array<string>>;

export function FetchMeterData(arg1:string,arg2:string):Promise<main.DeviceState>;

export function SendCustomCommand(arg1:string,arg2:string,arg3:string):Promise<string>;
